### ISSUE TITLE
symfony/console conflict during install

### ISSUE THREAD

**Issue by devdrops** [marcelsud/diffcs#10]
As noticed a few days ago, the installment process is affected by the following conflict: the symfony/console component with rigid criteria between v2.6.3 and v2.6.7.

![captura de tela 2015-07-13 as 11 48 43](https://cloud.githubusercontent.com/assets/1259313/8652454/2d1d68ba-2955-11e5-9a99-3e9f12ebad67.png)

**Comment by marcelsud** [comment]
Maybe we should add the "vendor" folder to the version control.

**Comment by marcelsud** [comment]
See [http://www.lornajane.net/posts/2014/using-composer-without-gitignoring](http://www.lornajane.net/posts/2014/using-composer-without-gitignoring)

**Comment by devdrops** [comment]
Hmm, maybe we should, but I don't see the reason to add the entire vendor to this repository. We may stuck this project with older package versions (knplabs/php-github-api is actually on release 1.5.*). Also I don't see how Packagist would react with this action on the project.
