### ISSUE TITLE
Validate files outside "download"

### ISSUE THREAD

**Issue by devdrops** [marcelsud/diffcs#7]
In order to prevent the break while downloading the files for scan, we've added the following validation (on [Executor.php class](https://github.com/marcelsud/diffcs/blob/master/src/Melody/Diffcs/Executor.php#L135)):

![captura de tela 2015-04-09 as 14 49 02](https://cloud.githubusercontent.com/assets/1259313/7073118/9c88ce5c-dec7-11e4-9100-e50cddb9f31a.png)

The idea is to move this validation to outside of the download scope, so we can download only files that exists, instead of download everything then check if the files already exist - avoiding lots of crap fixes.

**Comment by marcelsud** [comment]
I think that to move it outside is a great idea. But actually only the files that are not "removed" are downloaded.

**Comment by devdrops** [comment]
Yes, when the pull request related to this issue was accepted we skip the removed files from a pull request (merged on [7dc8028](https://github.com/marcelsud/diffcs/commit/7dc8028abe25a5e72021c3d319d03105e2c922aa)) :wink: 

So I'll close this issue, as the subject is already accepted.
